'use client';

import type { IssueTreeData } from './types';

/**
 * Export helpers for the Issue Tree.
 *
 * - exportJSON   — downloads the portable JSON shape (round-trips via Dexie)
 * - exportMarkdown — renders the tree as an indented Markdown list
 * - exportPNG    — uses html-to-image (loaded dynamically to keep the bundle thin)
 */

export function exportJSON(name: string, data: IssueTreeData) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  triggerDownload(blob, `${slug(name)}.tree.json`);
}

export function exportMarkdown(name: string, data: IssueTreeData) {
  const children: Record<string, string[]> = {};
  for (const e of data.edges) {
    (children[e.source] ||= []).push(e.target);
  }
  const byId = new Map(data.nodes.map((n) => [n.id, n] as const));

  const lines: string[] = [`# ${name}`, ''];

  function walk(id: string, depth: number) {
    const n = byId.get(id);
    if (!n) return;
    const indent = '  '.repeat(depth);
    lines.push(`${indent}- ${n.label}${n.note ? `  \n${indent}  _${n.note}_` : ''}`);
    for (const child of children[id] ?? []) walk(child, depth + 1);
  }

  walk(data.rootId, 0);
  lines.push('', '---', '*Generated by Case Arena · case-arena.app*');

  const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
  triggerDownload(blob, `${slug(name)}.tree.md`);
}

export async function exportPNG(name: string, element: HTMLElement) {
  try {
    const mod = await import('html-to-image');
    const dataUrl = await mod.toPng(element, {
      cacheBust: true,
      backgroundColor: 'transparent',
      pixelRatio: 2,
    });
    const a = document.createElement('a');
    a.href = dataUrl;
    a.download = `${slug(name)}.tree.png`;
    a.click();
  } catch (e) {
    console.error('[issue-tree] PNG export failed', e);
    throw e;
  }
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40) || 'tree';
}
